import { useState } from "react";
import { Zap, Droplets, Flame, Wifi, Phone, Info, Sparkles, TrendingDown, CheckCircle, Download } from "lucide-react";
import { API } from "../api";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import toast from "react-hot-toast";
import { Bar } from 'react-chartjs-2';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend,
} from 'chart.js';

ChartJS.register(
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend
);

function BillOptimizer() {
  const [form, setForm] = useState({
    billCategory: "Electricity",
    totalUnits: "",
    currentAmount: "",
    pricePerUnit: "",
    notes: ""
  });
  const [taxes, setTaxes] = useState([]);
  const [billResult, setBillResult] = useState(null);
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!form.currentAmount || !form.pricePerUnit) {
      return toast.error("Please fill current amount and price per unit");
    }

    setLoading(true);
    try {
      const res = await API.post("/bill-suggestions/add", { ...form, taxes });
      setBillResult(res.data.bill);
      toast.success("✅ Optimization report generated");
    } catch (err) {
      console.error(err);
      toast.error("❌ Error generating suggestions");
    } finally {
      setLoading(false);
    }
  };

  const downloadPDF = () => {
    if (!billResult) return;

    const doc = new jsPDF();
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(255, 120, 0);
    doc.text("SmartBill Optimizer", 105, 15, null, null, "center");

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text("Generated by AI Savings Engine", 105, 22, null, null, "center");
    doc.line(15, 28, 195, 28);

    autoTable(doc, {
      startY: 35,
      head: [['Category', 'Current Bill', 'Price/Unit', 'Potential Savings']],
      body: [
        [billResult.billCategory, `Rs ${billResult.currentAmount}`, `Rs ${billResult.pricePerUnit || 'N/A'}`, `Rs ${billResult.savingsEstimate}`],
      ],
      theme: 'grid',
      headStyles: { fillColor: [255, 120, 0], textColor: 255 },
    });

    let finalY = doc.lastAutoTable.finalY + 10;
    doc.setFontSize(14);
    doc.text("AI Suggestion", 14, finalY);
    doc.setFontSize(11);
    doc.setTextColor(50);
    const splitText = doc.splitTextToSize(billResult.aiSuggestion, 180);
    doc.text(splitText, 14, finalY + 6);

    doc.save(`SmartBill_Optimization_${billResult.billCategory}.pdf`);
  };

  const categories = [
    { name: "Electricity", icon: <Zap size={20} />, color: "text-amber-400" },
    { name: "Water", icon: <Droplets size={20} />, color: "text-blue-400" },
    { name: "Gas", icon: <Flame size={20} />, color: "text-orange-400" },
    { name: "Internet", icon: <Wifi size={20} />, color: "text-purple-400" },
    { name: "Phone", icon: <Phone size={20} />, color: "text-green-400" },
  ];

  return (
    <div className="min-h-screen pt-24 pb-12 px-6 bg-slate-50">
      <div className="max-w-6xl mx-auto grid grid-cols-1 lg:grid-cols-2 gap-10">

        {/* Input Section */}
        <div className="bg-white border border-slate-100 p-8 rounded-3xl shadow-2xl h-fit">
          <div className="flex items-center gap-3 mb-8">
            <div className="p-3 bg-orange-500/10 rounded-2xl text-orange-500">
              <TrendingDown size={28} />
            </div>
            <div>
              <h2 className="text-3xl font-black text-slate-900">Bill Optimizer</h2>
              <p className="text-slate-500 text-sm font-medium">Get AI-driven cost reduction strategies.</p>
            </div>
          </div>

          <form onSubmit={handleSubmit} className="space-y-6">
            <div>
              <label className="text-slate-400 text-sm font-bold uppercase tracking-wider mb-3 block">Category</label>
              <div className="grid grid-cols-3 sm:grid-cols-5 gap-3">
                {categories.map((cat) => (
                  <button
                    key={cat.name}
                    type="button"
                    onClick={() => setForm({ ...form, billCategory: cat.name })}
                    className={`flex flex-col items-center gap-2 p-3 rounded-2xl border transition-all ${form.billCategory === cat.name
                      ? "bg-orange-500/10 border-orange-500/20 text-orange-600 scale-105"
                      : "bg-slate-50 border-slate-200 text-slate-400 hover:border-orange-100"
                      }`}
                  >
                    {cat.icon}
                    <span className="text-[10px] font-bold">{cat.name}</span>
                  </button>
                ))}
              </div>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="text-slate-400 text-sm font-bold uppercase tracking-wider mb-2 block tracking-tight">Current Bill (Rs)</label>
                <input
                  type="number"
                  className="w-full bg-slate-50 border border-slate-200 p-4 rounded-xl focus:ring-2 focus:ring-orange-500 outline-none text-slate-900 transition-all font-mono"
                  placeholder="0.00"
                  value={form.currentAmount}
                  onChange={(e) => setForm({ ...form, currentAmount: e.target.value })}
                />
              </div>
              <div>
                <label className="text-slate-400 text-sm font-bold uppercase tracking-wider mb-2 block">Price Per Unit (Rs)</label>
                <input
                  type="number"
                  step="0.01"
                  className="w-full bg-slate-50 border border-slate-200 p-4 rounded-xl focus:ring-2 focus:ring-orange-500 outline-none text-slate-900 transition-all font-mono"
                  placeholder="0.00"
                  value={form.pricePerUnit}
                  onChange={(e) => setForm({ ...form, pricePerUnit: e.target.value })}
                />
              </div>
            </div>

            {/* Taxes Section */}
            <div>
              <div className="flex justify-between items-center mb-3">
                <label className="text-slate-400 text-sm font-bold uppercase tracking-wider">Taxes</label>
                <button
                  type="button"
                  onClick={() => setTaxes([...taxes, { name: "", amount: "" }])}
                  className="px-4 py-2 bg-orange-500/10 text-orange-600 rounded-lg text-xs font-bold hover:bg-orange-500/20 transition-all"
                >
                  + Add Tax
                </button>
              </div>

              {taxes.length > 0 && (
                <div className="space-y-3">
                  {taxes.map((tax, index) => (
                    <div key={index} className="flex gap-2">
                      <input
                        type="text"
                        className="flex-1 bg-slate-50 border border-slate-200 p-3 rounded-xl focus:ring-2 focus:ring-orange-500 outline-none text-slate-900 transition-all"
                        placeholder="Tax Name"
                        value={tax.name}
                        onChange={(e) => {
                          const newTaxes = [...taxes];
                          newTaxes[index].name = e.target.value;
                          setTaxes(newTaxes);
                        }}
                      />
                      <input
                        type="number"
                        step="0.01"
                        className="w-32 bg-slate-50 border border-slate-200 p-3 rounded-xl focus:ring-2 focus:ring-orange-500 outline-none text-slate-900 transition-all font-mono"
                        placeholder="Amount"
                        value={tax.amount}
                        onChange={(e) => {
                          const newTaxes = [...taxes];
                          newTaxes[index].amount = e.target.value;
                          setTaxes(newTaxes);
                        }}
                      />
                      <button
                        type="button"
                        onClick={() => setTaxes(taxes.filter((_, i) => i !== index))}
                        className="px-3 py-2 bg-red-500/10 text-red-600 rounded-xl hover:bg-red-500/20 transition-all font-bold"
                      >
                        ✕
                      </button>
                    </div>
                  ))}
                </div>
              )}
            </div>

            <div>
              <label className="text-slate-400 text-sm font-bold uppercase tracking-wider mb-2 block">Units Consumed (kWh/Gal)</label>
              <input
                type="number"
                className="w-full bg-slate-50 border border-slate-200 p-4 rounded-xl focus:ring-2 focus:ring-orange-500 outline-none text-slate-900 transition-all font-mono"
                placeholder="Ex: 350"
                value={form.totalUnits}
                onChange={(e) => setForm({ ...form, totalUnits: e.target.value })}
              />
            </div>

            <div>
              <label className="text-slate-400 text-sm font-bold uppercase tracking-wider mb-2 block">Detailed Notes</label>
              <textarea
                className="w-full bg-slate-50 border border-slate-200 p-4 rounded-xl focus:ring-2 focus:ring-orange-500 outline-none text-slate-900 transition-all min-h-[100px]"
                placeholder="Any specific usage patterns or concerns..."
                value={form.notes}
                onChange={(e) => setForm({ ...form, notes: e.target.value })}
              />
            </div>

            <button
              type="submit"
              className="w-full bg-gradient-to-r from-orange-600 to-orange-500 hover:from-orange-500 hover:to-orange-400 text-white p-5 rounded-2xl font-black text-lg shadow-lg shadow-orange-500/20 transition-all flex items-center justify-center gap-3 group"
              disabled={loading}
            >
              {loading ? (
                <>
                  <div className="w-6 h-6 border-4 border-white/20 border-t-white rounded-full animate-spin"></div>
                  Generating Report...
                </>
              ) : (
                <>
                  Optimize Bill
                  <Sparkles size={22} className="group-hover:rotate-12 transition-transform" />
                </>
              )}
            </button>
          </form>
        </div>

        {/* Result Section */}
        <div className="space-y-6">
          {!billResult ? (
            <div className="h-full bg-white border-2 border-dashed border-slate-200 rounded-3xl flex flex-col items-center justify-center p-12 text-center group">
              <div className="w-20 h-20 bg-slate-50 rounded-full flex items-center justify-center mb-6 group-hover:scale-110 transition-transform">
                <Info size={40} className="text-slate-300" />
              </div>
              <h3 className="text-2xl font-bold text-slate-400">No report generated yet.</h3>
              <p className="text-slate-500 max-w-xs mt-2">Fill in your bill details to get AI suggestions and savings analysis.</p>
            </div>
          ) : (
            <div className="space-y-6 animate-in slide-in-from-right duration-500">
              {/* Savings Card */}
              <div className="bg-gradient-to-br from-orange-500/10 to-amber-600/10 border border-orange-500/20 p-8 rounded-3xl shadow-sm">
                <div className="flex justify-between items-start mb-6">
                  <div>
                    <h3 className="text-slate-500 font-bold uppercase tracking-widest text-xs mb-1">Estimated Monthly Savings</h3>
                    <div className="text-5xl font-black text-slate-900">Rs {billResult.savingsEstimate}</div>
                  </div>
                  <div className="p-4 bg-orange-600 rounded-2xl text-white">
                    <TrendingDown size={32} />
                  </div>
                </div>
                <div className="flex items-center gap-2 text-orange-600 font-bold">
                  <CheckCircle size={18} />
                  Based on AI usage analysis
                </div>
              </div>

              {/* Chart Card */}
              <div className="bg-white border border-slate-100 p-6 rounded-3xl shadow-sm">
                <h4 className="text-slate-900 font-bold mb-4 flex items-center gap-2">
                  <TrendingDown size={18} className="text-orange-500" />
                  Bill Comparison View
                </h4>
                <div className="h-64">
                  {billResult.graphData && (
                    <Bar
                      data={billResult.graphData}
                      options={{
                        responsive: true,
                        maintainAspectRatio: false,
                        plugins: {
                          legend: { display: false },
                        },
                        scales: {
                          y: { grid: { color: "#f1f5f9" }, ticks: { color: "#64748b" } },
                          x: { grid: { display: false }, ticks: { color: "#64748b" } }
                        }
                      }}
                    />
                  )}
                </div>
              </div>

              {/* Suggestions Card */}
              <div className="bg-white border border-slate-100 p-8 rounded-3xl shadow-sm">
                <h4 className="text-orange-600 font-black uppercase tracking-widest text-xs mb-4">AI Optimization Insights</h4>
                <div className="prose prose-orange max-w-none">
                  <p className="text-slate-600 italic leading-relaxed whitespace-pre-line border-l-4 border-orange-500 pl-6 py-2">
                    {billResult.aiSuggestion}
                  </p>
                </div>
                <button
                  onClick={downloadPDF}
                  className="mt-8 w-full py-4 border border-slate-200 rounded-xl text-slate-900 font-bold hover:bg-slate-50 transition-all flex items-center justify-center gap-2 shadow-sm"
                >
                  <Download size={18} className="text-orange-600" />
                  Download Summary Report
                </button>
              </div>
            </div>
          )}
        </div>

      </div>
    </div>
  );
}

export default BillOptimizer;
